V2 addon
villander/ember-engines-router-service pull request #58
Opened 2022-02-09 08:53 UTC by AnastasiiaPlutalova

2022-02-10 16:46 UTC, SergeAstapov requested changes

2022-02-10 16:46 UTC, SergeAstapov commented on .github/workflows/ci.yml
> +    working-directory: test-app
@AnastasiiaPlutalova minor, we don't need this line as we specify `working-directory` below for tasks

2022-02-10 16:46 UTC, SergeAstapov commented on addon/package.json
> +    "babel-eslint": "^10.1.0",
@AnastasiiaPlutalova all of the eslint, ember-template-lint, npm-run-all and prettier should be in devDependencies

2022-02-10 16:46 UTC, SergeAstapov commented on .github/workflows/ci.yml
>    test:
@AnastasiiaPlutalova please adjust `floating` and `try-scenarios` as well to set `working-directory`

2022-02-11 09:58 UTC, AnastasiiaPlutalova commented on .github/workflows/ci.yml
>    test:
@SergeAstapov added `working-directory: test-app` to floating and try-scenarios. Is `working-directory: addon` is needed for them?

2022-02-11 09:58 UTC, AnastasiiaPlutalova commented on addon/package.json
> +    "babel-eslint": "^10.1.0",
Done

2022-02-11 09:58 UTC, AnastasiiaPlutalova commented on .github/workflows/ci.yml
> +    working-directory: test-app
Done

2022-02-11 14:40 UTC, SergeAstapov approved these changes

2022-02-26 01:07 UTC, villander commented
@SergeAstapov there's no CI running here, could you please fix that

2022-02-26 02:39 UTC, SergeAstapov commented
> First-time contributors need a maintainer to approve running workflows. 

@villander you need to approve PR to run CI :)

2022-03-01 13:54 UTC, villander approved these changes

2022-03-02 17:59 UTC, merged